apiVersion: apps/v1
kind: Deployment
metadata:
  name: drugs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drugs-pod
  template:
    metadata:
      labels:
        app: drugs-pod
    spec:
      containers:
      - name: drugs
        image: deepankar06/drugs:1.0
