apiVersion: v1
kind: Service
metadata:
  name: frontend-to-auth
spec:
  type: ClusterIP # internal communication
  ports:
  - targetPort: 44372 # port where backend is exposed
    port: 80 # port where service is exposed
  selector:
    tier: authorization-pod
    app: frontend-pod

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-servicespec:
# spec:
#   type: ClusterIP # internal communication
#   - targetPort: 80 # port where backend is exposed
#     port: 80 # port where service is exposed
#   selector:
#     tier: authorization-pod
#     app: refill-pod


