apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-pod
  template:
    metadata:
      labels:
        app: authorization-pod
    spec:
      containers:
      - name: authorization
        image: deepankar06/authorization:1.0
        ports:
        - containerPort: 44372
