apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      type: frontend-auth
  template:
    metadata:
      labels:
        app: frontend
        type: frontend-auth
    spec:
      containers:
      - name: frontend
        image: deepankar06/frontend:1.0
